config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "students#index"

  resources :students, shallow: true do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of :description,
                        :street,
                        :city,
                        :state,
                        :zipcode
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name
  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
    @student = Student.find(params[:student_id])
    @address = Address.new()
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render :edit
    end
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<h2>create a new address here</h2>

<%= form_for @address do |f| %>
  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :street %>
  <%= f.text_field :street %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zipcode %>
  <%= f.number_field :zipcode %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBasicsChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h2>edit <%= @student.name %> here</h2>

<%= render partial: "form" %>

<%= link_to "new student", new_student_path %>
<%= link_to "all students", students_path %>

app/views/students/index.html.erb
<% @students.each do |student| %>
  <li class=student_<%= student.id %>>
  <%= link_to "#{student.name}", student_path(student) %>
  <%= link_to "Edit", edit_student_path(student) %>
  <%= link_to "Delete", student_path(student), method: "delete" %>
  </li>
  <br>
<% end %>
<%= link_to "new student", new_student_path %>
<%= link_to "all students", students_path %>

app/views/students/new.html.erb
<h2>Create a new student here!</h2>

<%= render partial: "form" %>

<%= link_to "new student", new_student_path %>
<%= link_to "all students", students_path %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<%= link_to "edit", edit_student_path(@student) %>
<%= link_to "new student", new_student_path %>
<%= link_to "all students", students_path %>